services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

  app:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # (Optional) Specify the Dockerfile name if it's not 'Dockerfile'
      args:
        # (Optional) Build arguments to pass to the Dockerfile
        ENV: production
    container_name: taxi_ingest_app
    #pass command argments to run ingest_data.py via command
    command:
      - "--user=root"
      - "--password=root"
      - "--host=pgdatabase"
      - "--port=5432"
      - "--db=ny_taxi"
      - "--table_names"
      - "yellow_taxi_trips"
      - "lookup_table"
      - "--urls"
      - "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz"
      - "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"
    depends_on:
      - pgdatabase
